server:
  port: 8050
spring:
  datasource:
    username: root
    password: Yyqx1128!@
    url: jdbc:mysql://127.0.0.1:3306/dataselectdbx
    driver-class-name: com.mysql.cj.jdbc.Driver
# application.yml
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    # 配置 mapper 接口所在包的日志级别为 DEBUG，MyBatis 会输出执行的 SQL 及参数等信息
    org.journey.dao: DEBUG
