server:
  port: 8050
spring:
  datasource:
    username: root
    password: Yyqx1128!@
    url: jdbc:mysql://127.0.0.1:3306/dataselectdbx
    driver-class-name: com.mysql.cj.jdbc.Driver
# application.yml
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isActive
      logic-delete-value: 0
      logic-not-delete-value: 1
logging:
  level:
    # 配置 mapper 接口所在包的日志级别为 DEBUG，MyBatis 会输出执行的 SQL 及参数等信息
    org.journey.dao: DEBUG
    org.springframework.web.servlet: DEBUG
    org.apache.tomcat.jsp: DEBUG
